[versions]
kotlinx-coroutines = "1.10.2"
lwjgl = "3.4.1"
jni-utils = "0.1.7"
compose = "1.11.0-alpha02"
kotlin = "2.3.10"

[libraries]
kotlinx-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-debug = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-debug", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-jdk8 = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-jdk8", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-jdk9 = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-jdk9", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-slf4j = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-slf4j", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-swing = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-swing", version.ref = "kotlinx-coroutines" }

lwjgl-bom = { group = "org.lwjgl", name = "lwjgl-bom", version.ref = "lwjgl" }
lwjgl-core = { group = "org.lwjgl", name = "lwjgl", version.ref = "lwjgl" }
lwjgl-glfw = { group = "org.lwjgl", name = "lwjgl-glfw", version.ref = "lwjgl" }
lwjgl-opengl = { group = "org.lwjgl", name = "lwjgl-opengl", version.ref = "lwjgl" }

skiko-awt = { group = "org.jetbrains.skiko", name = "skiko-awt" }

jni-utils = { group = "dev.silenium.libs.jni", name = "jni-utils", version.ref = "jni-utils" }
slf4j-api = { group = "org.slf4j", name = "slf4j-api", version = "2.0.17" }
logback-classic = { group = "ch.qos.logback", name = "logback-classic", version = "1.5.20" }

[plugins]
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
compose = { id = "org.jetbrains.compose", version.ref = "compose" }
bytebuddy = { id = "net.bytebuddy.byte-buddy-gradle-plugin", version = "1.17.7" }

[bundles]
kotlinx-coroutines = [
    "kotlinx-coroutines-core",
    "kotlinx-coroutines-debug",
    "kotlinx-coroutines-jdk8",
    "kotlinx-coroutines-jdk9",
    "kotlinx-coroutines-slf4j",
    "kotlinx-coroutines-swing",
]

skiko = [
    "skiko-awt",
]

lwjgl = [
    "lwjgl-core",
    "lwjgl-glfw",
    "lwjgl-opengl",
]
